version: "3.9"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/code
    environment:
      FLASK_APP: "src/app.py"
      FLASK_ENV: "development"
      FLASK_RUN_HOST: "0.0.0.0"
      APP_SETTINGS: "api.configuration.config.DevelopmentConfig"
